// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUJzOWDQ6hA4CxYrEww3PKDVuZUtniXOo',
    appId: '1:103301243361:web:7b987cb1240b2c3429f2a0',
    messagingSenderId: '103301243361',
    projectId: 'farmpilot-646c1',
    authDomain: 'farmpilot-646c1.firebaseapp.com',
    storageBucket: 'farmpilot-646c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3CAIiP_u0X0PaJBw-XbLELtXKDSOe-Bo',
    appId: '1:103301243361:android:bb3dc129d1bb1bec29f2a0',
    messagingSenderId: '103301243361',
    projectId: 'farmpilot-646c1',
    storageBucket: 'farmpilot-646c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfhA5CMhyOuVyVdfD-lI9Oy_ejwSkllQ',
    appId: '1:103301243361:ios:3ea049220369dcfd29f2a0',
    messagingSenderId: '103301243361',
    projectId: 'farmpilot-646c1',
    storageBucket: 'farmpilot-646c1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfhA5CMhyOuVyVdfD-lI9Oy_ejwSkllQ',
    appId: '1:103301243361:ios:3ea049220369dcfd29f2a0',
    messagingSenderId: '103301243361',
    projectId: 'farmpilot-646c1',
    storageBucket: 'farmpilot-646c1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUJzOWDQ6hA4CxYrEww3PKDVuZUtniXOo',
    appId: '1:103301243361:web:43842ad2d1a47a0d29f2a0',
    messagingSenderId: '103301243361',
    projectId: 'farmpilot-646c1',
    authDomain: 'farmpilot-646c1.firebaseapp.com',
    storageBucket: 'farmpilot-646c1.firebasestorage.app',
  );
}
